import {identifyVariable} from "./src/mild/mild_2.js";
import {identifyArray} from "./src/mild/mild_2.js";
import { removeKey } from "./src/mild/mild_2.js";
import {removeKeyNonDestructive} from "./src/mild/mild_2.js";
import {removeKeys} from "./src/mild/mild_2.js";
import {getStatistics, getSum} from "./src/medium/medium_1.js";
import {getMedian} from "./src/medium/medium_1.js";
import mpg_data from "./src/medium/data/mpg_data.js";
import { allCarStats } from "./src/medium/medium_2.js";
import { searchHighPower } from "./src/medium/medium_3.js";
import { searchName } from "./src/medium/medium_3.js";
import { searchByYear } from "./src/medium/medium_3.js";
import { repeat } from "./src/spicy/spicy_9.js";
import { repeatDemo } from "./src/spicy/spicy_9.js";
import { everyEven } from "./src/spicy/spicy_9.js";
import { someEven } from "./src/spicy/spicy_9.js";
const stats = allCarStats;
console.log(someEven([4, 3, 2, 1, 0], x => x === 3));
console.log(someEven([1, 0, 1, 0, 1], x => x === 0));
console.log(someEven([1, 1, 1, 1, 0], x => x === 0));
console.log(someEven([0, 0, 0, 0, 0], x => x === 0));